<form action = '/newAirplane' method = 'Post'>
    <h4>Register a new plane:</h4>
    <div class="form-row">
        <div class="col">
            <input type="text" class="form-control" placeholder="Location" name="location">
        </div>
        <div class="col">
            <input type="text" class="form-control" placeholder="Passengers" name="passengers">
        </div>
        <div class="col">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>
