<h3>Iniciar Sessión</h3>
<form action = '/logIn' method = 'Post'>
  <div class="form-group">
    <label for="exampleInputEmail1">User name</label>
    <input type="text" class="form-control" name = 'userName'>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name = 'password'>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
<br>
<div>
    <a href='/signUp' button type="submit" class="btn btn-primary">Sign Up</a>
</div>