<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" 
        crossorigin="anonymous">
    <link rel="stylesheet" href="/css/file.css">
    
    <title>Phalcon Airport</title>
</head>
<body>
    <header>
        <h1>Airlines</h1>
    </header>
    <section>
        <nav>
            <ul>
            <li><a class="btn btn-primary btn-lg btn-block" data-toggle="collapse" role="button" aria-expanded="false" href="/flights">
            Flights
            </a></li>
            <li><a class="btn btn-primary btn-lg btn-block" data-toggle="collapse" role="button" aria-expanded="false" href="/airplanes">
            Airplanes</a></li>
            </ul>
        </nav>
        <?php echo $this->getContent(); ?>
    </section>
    <footer>
        <p>Footer</p>
    </footer>
</body>
</html>