<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" 
        crossorigin="anonymous">
    <style>
    * {
    box-sizing: border-box;
    }

    body {
    font-family: Arial, Helvetica, sans-serif;
    }

    /* Style the header */
    header {
        background-image: url("./sky.jpg");
        background-repeat: no-repeat;
        background-size:100% 100%;
        padding: 50px;
        text-align: center;
        font-size: 35px;
        color: white;
    }

    /* Create two columns/boxes that floats next to each other */
    nav {
    float: left;
    width: 15%;
    height: 300px; /* only for demonstration, should be removed */
    background: #99ccff;
    padding: 20px;
    }

    /* Style the list inside the menu */
    nav ul {
    list-style-type: none;
    padding: 0;
    }

    article {
    float: left;
    padding: 20px;
    width: 85%;
    background-color: white;
    height: 300px; /* only for demonstration, should be removed */
    }

    /* Clear floats after the columns */
    section:after {
    content: "";
    display: table;
    clear: both;
    }

    /* Style the footer */
    footer {
    background-color: #000099;
    padding: 10px;
    text-align: center;
    color: white;
    }

    /* Responsive layout - makes the two columns/boxes stack on top of each other instead of next to each other, on small screens */
    @media (max-width: 600px) {
    nav, article {
        width: 100%;
        height: auto;
        }
    }
    </style>
    <title>Phalcon Tutorial</title>
</head>
<body>
<div class="container">
    <?php echo $this->getContent(); ?>
</div>
</body>
</html>