<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" 
        crossorigin="anonymous">
    <link rel="stylesheet" href="/css/file.css">
    <script src="javascript/reloj.js"></script>
    
    <title>Phalcon Airport</title>
</head>
<body onload="mueveReloj()">
    <header>
        <h1>Airlines</h1>
    </header>
    <div class ="mainbody">
        <section>
            <nav>
                <form name="form_reloj">
                    <input type="text" name="reloj" size="10" disabled>
                </form>
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" href="/principal">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="/flights">Flights</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/airplanes">Airplanes</a>
                    </li>
                    <br><br><br>
                    <li class="nav-item">
                        <a class="nav-link" href="/signUp">Sign Up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/logOut">Log out</a>
                    </li>
                </ul>
            </nav>
            <?php echo $this->getContent(); ?>
        </section>
    </div>
    <footer>
        <p>Footer</p>
    </footer>
</body>
</html>