<div class='formu'>
    <form action = '/airplanes' method = 'Post'>
    <h4>Register a new plane:</h4>
    <div class="form-row">
        <div class="col">
            <input type="text" class="form-control" placeholder="Location" name="location">
        </div>
        <div class="col">
            <input type="number" class="form-control" placeholder="Passengers" name="passengers" min="1" max="255">
        </div>
        <div class="col">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>
<br>
<?php
if (!empty($message)) {
    echo '
    <div class="error">
    <p>Sorry, the following problems were generated: '.$message.'</p>
    </div>
    ';
}
?>
<a href="/airplanes">
    <img src="/icons/backIcon.svg" alt="" width="32" height="32">
</a>
</div>