<article>
  <h2>Controllers</h2>
  <p>Here you can register flights and airplanes in the data base, assign them destinations and set schedules.</p>
  <p>On the left, there are two redirect buttons:</p>
  <ul>
    <li><strong>Flights:</strong> It allows you to create flights with their respective origin and destination, plus a unique id. You can also see if the flight was assigned to a plane or if it has already been made.</li>
    <li><strong>Airplanes:</strong> It allows you to register planes with their number of seats, location, and unique id. In addition, you can assign flights and see their destinations.</li>
  </ul>
</article>