<div class = 'formu'>
  <h3>Sign up</h3>
  <form action = '/signUp' method = 'Post'>
    <div class="form-group">
      <label for="exampleInputEmail1">User name</label>
      <input type="text" class="form-control" name = 'userName'>
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Password</label>
      <input type="password" class="form-control" id="exampleInputPassword1" name = 'password'>
    </div>
    <button type="submit" class="btn btn-primary">Sign Up</button>
  </form>
  <br>
  <div>
      <a href='/' button type="submit" class="btn btn-primary">Back</a>
  </div>
  <div>
      <?php echo $this->getContent(); ?>
  </div>
</div>